#spring.application.name=movieticketing
#spring.datasource.url=jdbc:postgresql://localhost:5433/movieticketing
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=postgres
#spring.datasource.password=7412369
#spring.jpa.show-sql=true
#spring.batch.job.enabled=false
#
#org.apache.jasper.compiler.TldLocationsCache.level = FINE
#org.apache.jasper.servlet.TldScanner.level = FINE
#
#spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect

server:
    error:
    include-message: always
    include-binding-errors: always

spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/movieticketing
        driver-class-name: org.postgresql.Driver
        password: 7412369
        username: postgres
    security:
        user:
            name: shabnam
            password: 7412369

jpa:
    hibernate:
        ddl-auto: create-drop
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
    show-sql: true

mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
        mail:
            smtp:
                ssl:
                    trust: "*"
                auth: true
                starttls:
                    enable: true
                connectiontimeout: 5000
                timeout: 3000
                writetimeout: 5000




#spring.security.user.name=shabnam
#spring.security.user.password=7412369
